parameters:
    locale: "%kernel.default_locale%"

framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: true
    #http_method_override: true

    #esi: true
    #fragments: true
    php_errors:
        log: true

    form:            ~
    csrf_protection: ~
    validation:
        enable_annotations: true
        enabled: true
    #serializer:      { enable_annotations: true }
    default_locale:  "en"
    trusted_hosts:   ~
#    error_controller:  Symfony\\Bundle\\TwigBundle\\Controller\\ExceptionController::showAction

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        cookie_lifetime: 28800
        cookie_samesite: 'strict'
        gc_probability: null

    fragments:       ~
    http_method_override: true
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
    translator: { fallbacks: [en] }
#    cache:
        # Put the unique name of your app here: the prefix seed
        # is used to compute stable namespaces for cache keys.
        #prefix_seed: bevolunteer/rox

        # The app cache caches to the filesystem by default.
        # Other options include:

        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu
